# POST http://localhost:4141/api/student/addstudent
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsicmVjb3Jkc2V0cyI6W1t7InN0dWRlbnRpZCI6Miwic3R1ZGVudG5hbWUiOiJOb29yLUxhZGR1IiwiYWdlIjo1LCJhZGRyZXNzIjoiUGF0aWFsYSIsInVzZXJuYW1lIjoibm9vciIsInBhc3N3b3JkIjoiJDJiJDEwJDRJNDRic1pyOVBJS05oNkpKblY2MGVadENtYXhKOXlZWWpWYW5uOVZXMlFGeUxiVnIvaWVXIn1dXSwicmVjb3Jkc2V0IjpbeyJzdHVkZW50aWQiOjIsInN0dWRlbnRuYW1lIjoiTm9vci1MYWRkdSIsImFnZSI6NSwiYWRkcmVzcyI6IlBhdGlhbGEiLCJ1c2VybmFtZSI6Im5vb3IiLCJwYXNzd29yZCI6IiQyYiQxMCQ0STQ0YnNacjlQSUtOaDZKSm5WNjBlWnRDbWF4Sjl5WVlqVmFubjlWVzJRRnlMYlZyL2llVyJ9XSwib3V0cHV0Ijp7fSwicm93c0FmZmVjdGVkIjpbMV0sInJldHVyblZhbHVlIjowfSwiaWF0IjoxNjEyNDYwNTExLCJleHAiOjE2MTI0NjQxMTF9.MRRktrlwjEt9DqJvSaBKBlFduiOtysBMNvdxVi85zHA

# {
#     "studentid": 0,
#     "studentname": "sirat",
#     "age": 5,
#     "address": "na",
#     "username":"sirat",
#     "password":"admin"
# }

GET http://localhost:4141/api/student/getstudentbyid/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsicmVjb3Jkc2V0cyI6W1t7InN0dWRlbnRpZCI6Miwic3R1ZGVudG5hbWUiOiJOb29yLUxhZGR1IiwiYWdlIjo1LCJhZGRyZXNzIjoiUGF0aWFsYSIsInVzZXJuYW1lIjoibm9vciIsInBhc3N3b3JkIjoiJDJiJDEwJDRJNDRic1pyOVBJS05oNkpKblY2MGVadENtYXhKOXlZWWpWYW5uOVZXMlFGeUxiVnIvaWVXIn1dXSwicmVjb3Jkc2V0IjpbeyJzdHVkZW50aWQiOjIsInN0dWRlbnRuYW1lIjoiTm9vci1MYWRkdSIsImFnZSI6NSwiYWRkcmVzcyI6IlBhdGlhbGEiLCJ1c2VybmFtZSI6Im5vb3IiLCJwYXNzd29yZCI6IiQyYiQxMCQ0STQ0YnNacjlQSUtOaDZKSm5WNjBlWnRDbWF4Sjl5WVlqVmFubjlWVzJRRnlMYlZyL2llVyJ9XSwib3V0cHV0Ijp7fSwicm93c0FmZmVjdGVkIjpbMV0sInJldHVyblZhbHVlIjowfSwiaWF0IjoxNjEyNDYwNTExLCJleHAiOjE2MTI0NjQxMTF9.MRRktrlwjEt9DqJvSaBKBlFduiOtysBMNvdxVi85zHA

